spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: fundcompass

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/fundcompass}
    username: ${DB_USERNAME:fundcompass}
    password: ${DB_PASSWORD:localdev}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.orm.jdbc.bind: info
    com.fundcompass.program.service.BizinfoProgramMapper: debug
    org.apache.pdfbox: error
    org.apache.fontbox: error

bizinfo:
  api:
    base-url:
      https://www.bizinfo.go.kr/uss/rss/bizinfoApi.do
    key: ${BIZINFO_API_KEY:}


fundcompass:
  scheduler:
    program-sync:
      enabled: ${PROGRAM_SYNC_ENABLED:false} # 배포에서 환경변수로만
      cron: "0 30 4 * * *"