CREATE TABLE program (
                         id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- 기업마당 원본 식별자
                         pblanc_id               VARCHAR(50)  NOT NULL,
                         name                    VARCHAR(500) NOT NULL,
                         detail_url              VARCHAR(500),
                         summary_html            TEXT,
                         target_name             VARCHAR(500),

    -- 신청기간: 원본 문자열과 해석 결과를 함께 보관한다
                         apply_period_raw        VARCHAR(200),
                         deadline_type           VARCHAR(20)  NOT NULL,
                         apply_start_date        DATE,
                         apply_end_date          DATE,

    -- 기관·분야
                         supervising_institution VARCHAR(200),
                         executing_institution   VARCHAR(200),
                         field_large             VARCHAR(100),
                         field_middle            VARCHAR(100),
                         hashtags                VARCHAR(1000),

    -- 신청 안내
                         apply_method            TEXT,
                         contact                 VARCHAR(500),
                         attachment_name         VARCHAR(500),

    -- 기업마당 기준 시각
                         source_created_at       TIMESTAMP(6),
                         source_updated_at       TIMESTAMP(6),

    -- 우리 시스템 기준 시각
                         created_at              TIMESTAMP(6),
                         updated_at              TIMESTAMP(6),

                         CONSTRAINT uk_program_pblanc_id UNIQUE (pblanc_id),
                         CONSTRAINT program_deadline_type_check CHECK (
                             deadline_type IN ('FIXED_PERIOD', 'UNTIL_BUDGET', 'ALWAYS_OPEN',
                                               'FIRST_COME', 'VARIES', 'UNKNOWN')
                             )
);

CREATE INDEX idx_program_apply_end_date     ON program (apply_end_date);
CREATE INDEX idx_program_source_updated_at  ON program (source_updated_at);

COMMENT ON TABLE  program                IS '기업마당 지원사업 공고';
COMMENT ON COLUMN program.pblanc_id      IS '기업마당 공고 ID (멱등성 키)';
COMMENT ON COLUMN program.apply_period_raw IS '신청기간 원본 문자열 (파싱 실패 시에도 보존)';
COMMENT ON COLUMN program.deadline_type  IS '마감 유형. FIXED_PERIOD만 날짜를 갖는다';
COMMENT ON COLUMN program.source_updated_at IS '기업마당 기준 수정일시 (갱신 판단 기준)';