CREATE TABLE program_document (
                                  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  program_id     BIGINT       NOT NULL,

                                  file_name      VARCHAR(500),
                                  file_url       VARCHAR(500) NOT NULL,
                                  file_type      VARCHAR(20)  NOT NULL,
                                  status         VARCHAR(20)  NOT NULL,

                                  extracted_text TEXT,
                                  error_message  VARCHAR(500),
                                  extracted_at   TIMESTAMP(6),

                                  created_at     TIMESTAMP(6),
                                  updated_at     TIMESTAMP(6),

                                  CONSTRAINT fk_program_document_program
                                      FOREIGN KEY (program_id) REFERENCES program (id) ON DELETE CASCADE,
                                  CONSTRAINT uk_program_document_url UNIQUE (program_id, file_url),
                                  CONSTRAINT program_document_file_type_check
                                      CHECK (file_type IN ('PDF', 'HWP', 'IMAGE', 'OTHER')),
                                  CONSTRAINT program_document_status_check
                                      CHECK (status IN ('PENDING', 'EXTRACTED', 'UNSUPPORTED', 'FAILED'))
);

CREATE INDEX idx_program_document_status ON program_document (status);

COMMENT ON TABLE  program_document              IS '공고 첨부문서와 추출 텍스트';
COMMENT ON COLUMN program_document.file_type    IS '확장자 기준 분류. printFileNm이 PDF가 아닐 수 있으므로 확장자로 판단';
COMMENT ON COLUMN program_document.status       IS 'PENDING=대기, EXTRACTED=성공, UNSUPPORTED=미지원 포맷, FAILED=오류';
COMMENT ON COLUMN program_document.extracted_text IS '추출 텍스트. 원본 파일은 저장하지 않고 file_url로 재취득';