CREATE TABLE program_eligibility (
                                     id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     program_id     BIGINT      NOT NULL,
                                     status         VARCHAR(20) NOT NULL,

                                     extraction     JSONB,

                                     prompt_version VARCHAR(20) NOT NULL,
                                     model_id       VARCHAR(50) NOT NULL,
                                     prompt_chars   INTEGER,
                                     elapsed_ms     INTEGER,

                                     error_message  VARCHAR(500),
                                     extracted_at   TIMESTAMP(6),

                                     created_at     TIMESTAMP(6),
                                     updated_at     TIMESTAMP(6),

                                     CONSTRAINT fk_program_eligibility_program
                                         FOREIGN KEY (program_id) REFERENCES program (id) ON DELETE CASCADE,
                                     CONSTRAINT uk_program_eligibility_program UNIQUE (program_id),
                                     CONSTRAINT program_eligibility_status_check
                                         CHECK (status IN ('EXTRACTED', 'FAILED'))
);

CREATE INDEX idx_program_eligibility_status ON program_eligibility (status);

COMMENT ON TABLE  program_eligibility                IS '공고별 자격요건 추출 결과 (공고당 1행)';
COMMENT ON COLUMN program_eligibility.extraction     IS 'EligibilityExtraction 전체. 스키마가 계속 바뀌므로 JSONB로 담는다';
COMMENT ON COLUMN program_eligibility.status         IS 'EXTRACTED=성공, FAILED=데이터 오류. 429는 행을 만들지 않고 배치를 중단한다';
COMMENT ON COLUMN program_eligibility.prompt_version IS '프롬프트를 고치면 재추출이 필요하다. 버전이 없으면 어느 버전으로 뽑힌 값인지 섞인다';
COMMENT ON COLUMN program_eligibility.model_id       IS '모델을 바꿔 비교할 때 필요';
COMMENT ON COLUMN program_eligibility.prompt_chars   IS '토큰·비용 추정용 실측치';